version: '2'
services:
  hexfmp:
    build: ..
    command: mix dev
    ports:
      - "4000:4000"
    links:
      - postgres
    networks:
      - this_host_services

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hexpm_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    command: postgres
    networks:
      - this_host_services

networks:
  this_host_services:
    external: true

volumes:
  pgdata:
    driver: local
