version: '2'
services:
  hexfmp_test:
    build: ..
    command: mix test
    environment:
      - MIX_ENV=test
    links:
      - postgres
    networks:
      - this_host_services

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hexpm_test
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    command: postgres
    networks:
      - this_host_services

networks:
  this_host_services:
    external: true

volumes:
  pgdata:
    driver: local
