version: '2'
services:
  hexfmp_test:
    build: ..
    command: mix test
    logging:
      driver: "json-file"
    environment:
      - MIX_ENV=test
    links:
      - hexfmp_postgres_test
    networks:
      - this_host_services

  hexfmp_postgres_test:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hexpm_test
      - PGDATA=/var/lib/postgresql/data/pgdata
    command: postgres
    networks:
      - this_host_services

networks:
  this_host_services:
    external: true
